Added a few ServerCrashers
CCBlueX/LiquidBounce pull request #152
Opened 2020-08-31 11:38 UTC by ForyxCraft

2020-09-13 15:52 UTC, NurMarvin requested changes
Please change the things I've added comments on and then we'll consider merging this.

2020-09-13 15:52 UTC, NurMarvin commented on shared/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/ServerCrasher.kt
> +                println(book4.tagCompound.toString().toByteArray().size)
This debug line should be removed:
```suggestion
```

2020-09-13 15:52 UTC, NurMarvin commented on shared/main/java/net/ccbluex/liquidbounce/features/module/modules/exploit/ServerCrasher.kt
> +                object : Thread() {
It would be better to replace this with the [`thread` function that Kotlin provides](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.concurrent/thread.html):
```suggestion
                thread() {
                    ...
                }
```

2020-09-16 20:30 UTC, kawaiinekololi commented
Looks good, I didn't tried them yet but probably works. There are just a few debug println left and I'm not sure if it is a good idea to create a extra thread, but I'll merge it and improve it then.

2020-09-16 20:30 UTC, merged

2021-02-22 04:30 UTC, kawaiinekololi commented
https://youtu.be/rjFOdTJi5vQ
@ForyxCraft Könntest du uns bitte aufklären, wie es zu dem Code gekommen ist.

2021-03-03 22:36 UTC, ForyxCraft commented
@kawaiinekololi 
A friend gave me the permission to put the code he "wrote" in here. I just translated it to Kotlin.
Idk if they got it from Meta.
You can ofc remove it if you want to.