add speed potion to autopot
CCBlueX/LiquidBounce pull request #1635
Opened 2023-12-07 08:29 UTC by yoseph1247

2023-12-07 12:39 UTC, 1zun4 requested changes
The code simply does not compile.

2023-12-07 12:39 UTC, 1zun4 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleAutoPot.kt
> +        if (speedPotion) {
Might check if the player not already has the speed effect.

2023-12-07 16:27 UTC, Ell1ott commented
what about doing it like this: https://github.com/Ell1ott/LiquidBounce/commit/7c2c3527697b0f874fdf7e58c015a361730ec862

2023-12-07 17:09 UTC, yoseph1247 commented
👍

2023-12-07 18:07 UTC, Ell1ott approved these changes

2023-12-07 18:38 UTC, 1zun4 approved these changes

2023-12-08 06:56 UTC, yoseph1247 commented
i'm not 100% sure on how to fix this compiling issue, i'm not the greatest at coding

2023-12-10 13:39 UTC, be4dev commented
> i'm not 100% sure on how to fix this compiling issue, i'm not the greatest at coding

do you use IDEA?

2023-12-10 14:50 UTC, yoseph1247 commented
> > i'm not 100% sure on how to fix this compiling issue, i'm not the greatest at coding
> 
> do you use IDEA?

yeah but i wasn't using it for this because it's very laggy, seems to be fixed now and it does compile so

2023-12-10 15:06 UTC, be4dev commented
> > > i'm not 100% sure on how to fix this compiling issue, i'm not the greatest at coding
> > 
> > 
> > do you use IDEA?
> 
> yeah but i wasn't using it for this because it's very laggy, seems to be fixed now and it does compile so

you can try vscode or nvim with kotlin support plugin

2023-12-10 15:08 UTC, yoseph1247 commented
> > > > i'm not 100% sure on how to fix this compiling issue, i'm not the greatest at coding
> > > 
> > > 
> > > do you use IDEA?
> > 
> > 
> > yeah but i wasn't using it for this because it's very laggy, seems to be fixed now and it does compile so
> 
> you can try vscode or nvim with kotlin support plugin

it worked well enough, just gotta give it some extra time

2023-12-10 15:27 UTC, yoseph1247 commented
guess it doesnt compile but it compiles in my own ide...

2023-12-10 15:31 UTC, mems01 commented
It's a detekt issue, it doesn't like the code that is present in the isPotion function. Don't worry, I will try to fix it rq...

2023-12-10 15:41 UTC, mems01 commented
👍

2023-12-10 15:44 UTC, merged