feat: verus flat fly
CCBlueX/LiquidBounce pull request #3258
Opened 2024-06-17 21:06 UTC by liquidsquid1

adds a simple verus flat fly

the reason this works is verus becomes super dumb when you clip, so blinking with that allows you to infinitely air walk. on top of that, timer works with high pauses inbetween movement packets which means that any timer would work with the blink (as long as you are on 1.9.x or higher)

can rarely flag when moving whilst stopping, but i've set the velocity to 0 to combat that.

tested on anticheat-test AND loyisa

you can only land on the same Y level

2024-06-17 21:08 UTC, 1zun4 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/fly/modes/verus/FlyVerusFlat.kt
> +        if (event.packet is PlayerMoveC2SPacket) {
Put event.variable into extra variable

2024-06-17 21:13 UTC, liquidsquid1 commented
seems like detekt hates me, will fix tomorrow so that it compiles

2024-06-18 07:12 UTC, EclipsesDev commented
very complex condition real

2024-06-18 07:13 UTC, liquidsquid1 commented
> very complex condition real

has 8 conditions
i add 1 condition
now it says the max is 5?!!?

2024-07-06 10:12 UTC, 1zun4 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/fly/modes/verus/FlyVerusFlat.kt
> +internal object FlyVerusFlat : Choice("VerusFlat") {
Put the version name of Verus into the name, then I will merge it.

2024-07-06 10:13 UTC, 1zun4 requested changes
please add the version name to the fly name

2024-07-11 00:47 UTC, 1zun4 approved these changes

2024-07-11 00:47 UTC, merged