Add AntiBounce
CCBlueX/LiquidBounce pull request #3282
Opened 2024-06-21 00:51 UTC by ManInMyVan

Module to prevent bouncing on bouncy blocks. This bypasses most anticheats (even grim)

2024-06-21 02:46 UTC, EclipsesDev commented
Hmm so essentially this is just auto sneak (which prevent bounces) on bouncing blocks?

2024-06-21 03:06 UTC, ManInMyVan commented
> Hmm so essentially this is just auto sneak (which prevent bounces) on bouncing blocks?

It prevents bouncing on bouncing blocks as if the player was sneaking

2024-06-21 03:59 UTC, 1zun4 requested changes

2024-06-21 03:59 UTC, 1zun4 commented on src/main/java/net/ccbluex/liquidbounce/injection/mixins/minecraft/entity/MixinEntity.java
> +    @Redirect(method = "bypassesLandingEffects", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/Entity;isSneaking()Z"))
Do not use `@Redirect`. It cannot be stacked and might cause mod incompatibility. Use this instead: https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue

2024-06-22 08:44 UTC, 1zun4 approved these changes

2024-06-22 08:44 UTC, merged