Added more commands help and bind
CCBlueX/LiquidBounce pull request #330
Opened 2021-01-11 20:06 UTC by enderchickenbawk

- added Help command

- added Bind command

2021-01-14 10:17 UTC, kawaiinekololi commented on src/main/kotlin/net/ccbluex/liquidbounce/features/command/commands/BindCommand.kt
> +                e.printStackTrace();
Missing error handling on unknown keys (no user response)

2021-01-14 10:18 UTC, kawaiinekololi commented on src/main/kotlin/net/ccbluex/liquidbounce/features/command/commands/HelpCommand.kt
> +            .handler { args ->
Help command should automatically generate a list of commands with descriptions

2021-01-14 10:18 UTC, kawaiinekololi requested changes
read comments

2021-01-15 00:45 UTC, enderchickenbawk commented
ok
added automatic command list generation
added "invalid keybinding." to Exception in bind command

2021-01-16 12:27 UTC, kawaiinekololi commented
I appreciate your work, but it seems you don't really know how to write Kotlin code. I'll do it myself or might work on the pull request.

2021-01-20 00:56 UTC, merged