feat: restore-command and improve value-command
CCBlueX/LiquidBounce pull request #4003
Opened 2024-09-29 13:46 UTC by ccetl

- Adds a restore command, that restores original values
- Improves the value command: you now have auto-completion for certain settings and you can use it for sub-settings

2024-10-10 15:52 UTC, 1zun4 commented
How is the progress on this?

2024-10-10 17:03 UTC, ccetl commented
> How is the progress on this?

Done but not tested enough.

2024-10-26 18:27 UTC, 1zun4 commented
I think it has trouble to restore settings in Choices. It can reset the mode back on the default value, but it cannot reset the settings within the modes.

2024-10-26 18:27 UTC, 1zun4 requested changes
I think it has trouble to restore settings in Choices. It can reset the mode back on the default value, but it cannot reset the settings within the modes.

2024-10-26 21:24 UTC, ccetl commented
> I think it has trouble to restore settings in Choices. It can reset the mode back on the default value, but it cannot reset the settings within the modes.

Oh and you probably can't change them with the value-command either...

2025-02-20 12:56 UTC, ccetl commented
I'm too lazy to continue finish this.

2025-02-20 12:56 UTC, closed without merging