Update DisablerVulcanScaffold.kt
CCBlueX/LiquidBounce pull request #4181
Opened 2024-10-17 20:31 UTC by TheColorfulGabibbo

Fixed the disabler because it flags badpacket (P). That is caused by the sending of the sneak packet when the player is on air.

2024-10-19 03:56 UTC, ManInMyVan reviewed
Pretty sure this will reopen #2829

2024-10-19 03:56 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            }
```suggestion
            if (player.isOnGround && isTowering) {
                network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.PRESS_SHIFT_KEY))
                network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
            }
```

2024-10-19 03:56 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +
```suggestion

                 network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.PRESS_SHIFT_KEY))
                 network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
```

2024-10-19 09:27 UTC, EclipsesDev commented
pretty sure badpackets p is not caused by player on air only..

2024-10-19 11:25 UTC, TheColorfulGabibbo commented
@EclipsesDev it is working without a single badpackets flag so idk

2024-10-19 11:38 UTC, TheColorfulGabibbo commented
@ManInMyVan Xd why did i use else lmfao

2024-10-19 16:43 UTC, ManInMyVan requested changes

2024-10-19 16:43 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +        if ( player.isInFluid || player.isTouchingWater || player.isDead || player.isHoldingOntoLadder
```suggestion
        if (player.isInFluid || player.isTouchingWater || player.isDead || player.isHoldingOntoLadder
```

2024-10-19 16:43 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +        }
```suggestion
        network.sendPacket(ClientCommandC2SPacket(player,ClientCommandC2SPacket.Mode.START_SPRINTING))
        network.sendPacket(ClientCommandC2SPacket(player,ClientCommandC2SPacket.Mode.STOP_SPRINTING))
```

2024-10-19 16:43 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            }
```suggestion
        if (player.age % 9 == 0) {
            if (player.isOnGround && !isTellyBridging && !isTowering) {
                network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
            }
        }
```

2024-10-19 18:21 UTC, TheColorfulGabibbo commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +        }
im fucking dumb

2024-10-19 19:20 UTC, ManInMyVan requested changes

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +
```suggestion
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +             *We use probability to send unsneak when the player is on ground and is towering to fix the
```suggestion
             * We use probability to send unsneak when the player is on ground and is towering to fix the
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            /**
```suggestion
            /*
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +        //Fix for the disabler not triggering while telly bridging
```suggestion
        // Fix for the disabler not triggering while telly bridging
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            //if the player meets one of theese requirements we return to the handler or else it will flag
```suggestion
            // if the player meets one of theese requirements we return to the handler or else it will flag
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            network.sendPacket(ClientCommandC2SPacket(player,ClientCommandC2SPacket.Mode.STOP_SPRINTING))
```suggestion
        network.sendPacket(ClientCommandC2SPacket(player,ClientCommandC2SPacket.Mode.START_SPRINTING))
        network.sendPacket(ClientCommandC2SPacket(player,ClientCommandC2SPacket.Mode.STOP_SPRINTING))
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +                 }
```suggestion
             if (player.isOnGround && !isTellyBridging && !isTowering) {
                 network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
             }
```

2024-10-19 19:20 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> + * the last 15 ticks. By using packet to unsneak, you can exploit this check and
```suggestion
 * the last 15 ticks. By using packets to unsneak, you can exploit this check and
```

2024-10-19 19:23 UTC, TheColorfulGabibbo commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> + * the last 15 ticks. By using packet to unsneak, you can exploit this check and
bro become grammarly

2024-10-19 19:45 UTC, TheColorfulGabibbo commented
take the "#2" as a second code refactoring and not anything else Xd

2024-10-19 20:39 UTC, ManInMyVan requested changes

2024-10-19 20:39 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +/*
```suggestion
/**
```

2024-10-19 20:39 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +    }
```suggestion
        if (player.age % 9 == 0 && player.isOnGround && !isTellyBridging && !isTowering) {
            network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
        }
    }
}
```

2024-10-22 05:03 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
> +            // If the player meets one of theese requirements we return to the handler or else it will flag
pretty sure it's to prevent it running in useless scenarios

2024-10-22 05:03 UTC, ManInMyVan commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/exploit/disabler/disablers/DisablerVulcanScaffold.kt
>          }
```suggestion
            network.sendPacket(ClientCommandC2SPacket(player, ClientCommandC2SPacket.Mode.RELEASE_SHIFT_KEY))
        }
    }
}
```

2024-10-26 18:37 UTC, merged