better backtrack
CCBlueX/LiquidBounce pull request #4272
Opened 2024-10-27 11:34 UTC by larryngton2

- render modes
- chance to backtrack

### todo
- [ ] playermodel render mode
- [ ] refactor my shitcode
- [ ] more settings

2024-10-27 20:05 UTC, vardenixxxas commented
>want something in client
>make shit code for it
>force izuna to recode it

2024-10-27 20:07 UTC, larryngton2 commented
> want something in client make shit code for it force izuna to recode it

99% larryman
1% eyezuna

2024-10-27 20:14 UTC, superblaubeere27 requested changes

2024-10-27 20:14 UTC, superblaubeere27 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleBacktrack.kt
> +    private var delayForNextBacktrack = 0L
Use the `Chronometer` utility for that please

2024-10-27 20:14 UTC, superblaubeere27 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleBacktrack.kt
> +            delayForNextBacktrack = System.currentTimeMillis() + nextBacktrackDelay.random()
s.a.

2024-10-27 20:14 UTC, superblaubeere27 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleBacktrack.kt
> +            System.currentTimeMillis() >= delayForNextBacktrack
s.a.

2024-10-27 20:17 UTC, larryngton2 commented on src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleBacktrack.kt
> +            delayForNextBacktrack = System.currentTimeMillis() + nextBacktrackDelay.random()
can you translate to simple english

2024-10-29 05:08 UTC, EclipsesDev reviewed
Is this even needed?

2024-10-29 05:09 UTC, EclipsesDev commented
no wait wrong one xd

2024-10-29 11:32 UTC, larryngton2 commented
> no wait wrong one xd

well which is the correct one

2024-10-29 11:43 UTC, EclipsesDev commented
test @larryngton2

2024-10-29 11:43 UTC, larryngton2 commented
> test @larryngton2

tested successfully

2024-11-04 00:44 UTC, 1zun4 approved these changes
Code looks good but I have not tested.

2024-11-04 00:46 UTC, merged