feat(legacy): chatcontrol module
CCBlueX/LiquidBounce pull request #4836
Opened 2024-12-08 09:27 UTC by EclipsesDev

- [ ] Add StackMessage

Closes: #4243

2024-12-14 12:26 UTC, EclipsesDev commented
pr will be on pending

2024-12-24 06:30 UTC, Coccocoahelper commented
Progress?

2025-01-18 12:25 UTC, DataM0del requested changes
- Add a ToggleableConfigurable object like in Nextgen so the module settings aren't cluttered, and use that here for the settings for each of these.
- chatControl in hookChatClear is declared as final, be consistent & make `chatControl` in `hookNoLengthLimit` final.

2025-01-18 12:25 UTC, DataM0del commented on src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/gui/MixinGuiNewChat.java
> +        ChatControl chatControl = ChatControl.INSTANCE;
```suggestion
        final ChatControl chatControl = ChatControl.INSTANCE;
```

`chatControl` in `hookChatClear` is declared as final, why not be consistent?

2025-01-18 12:25 UTC, DataM0del commented on src/main/java/net/ccbluex/liquidbounce/injection/forge/mixins/packets/MixinC01PacketChatMessage.java
> +    public void injectForceUnicodeChat(String p_i45240_1_, CallbackInfo ci) {
Searge be like:
:x: map the parameter names
:heavy_check_mark: leave it there, happens 99.99% of the time.

2025-01-18 12:25 UTC, DataM0del commented on src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/ChatControl.kt
> +    val forceUnicodeChat by boolean("ForceUnicodeChat", false)
Add a `ToggleableConfigurable` object like in Nextgen so the module settings aren't cluttered, and use that here for the settings for each of these.

2025-01-27 23:18 UTC, opZywl commented
add second chat pleas

![image](https://github.com/user-attachments/assets/1ee77422-3a26-4cfc-959d-996a528adc4d)

2025-03-01 16:48 UTC, closed without merging