feat: Script debug command
CCBlueX/LiquidBounce pull request #5129
Opened 2024-12-31 18:39 UTC by commandblock2

Implement a part of issue https://github.com/CCBlueX/LiquidBounce/issues/4982
Added a client sub command to enable placing break points in scripts. The command has following parameters:
`.client debug <name> [<protocol>] [<suspendOnStart>] [<inspectInternals>] [<port>]`.
Protocols includes [DAP](https://www.graalvm.org/latest/tools/dap/) and inspect([Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/)).

See the video demo for more details.

https://github.com/user-attachments/assets/a86b1bde-4787-4001-9d68-d9b532314c68

This pr does **NOT** include a dedicated module for REPL or a debug view using the embedded MCEF browser, because MCEF does not come with a bundled devtools, we might have to host this devtool and it might not be a good idea to have the possibility to put a breakpoint on the render thread that could freeze the game itself irrecoverably.

2024-12-31 18:42 UTC, commandblock2 commented on build.gradle
for the `.script debug` to be functional, [chromeinspector](https://mvnrepository.com/artifact/org.graalvm.tools/chromeinspector-tool/24.0.2) might be sufficient, but the tools-community also includes a lsp and other tools that maybe useful for future features like code completions or script profiling etc.

2024-12-31 23:27 UTC, sqlerrorthing requested changes

2024-12-31 23:27 UTC, sqlerrorthing commented on src/main/kotlin/net/ccbluex/liquidbounce/script/PolyglotScript.kt
> +                            regular("Script $file is configured to launch with debugger support on: ")
add a translation?

2024-12-31 23:27 UTC, sqlerrorthing commented on src/main/kotlin/net/ccbluex/liquidbounce/script/PolyglotScript.kt
> +                                                        "(unfortunately only chromium based browser will work)"
add a translation?

2024-12-31 23:27 UTC, sqlerrorthing commented on src/main/kotlin/net/ccbluex/liquidbounce/script/PolyglotScript.kt
> +                            throw IllegalStateException("Debug port ${debugOptions.port} already in use", e)
add a translation?

2024-12-31 23:27 UTC, sqlerrorthing commented on src/main/kotlin/net/ccbluex/liquidbounce/script/PolyglotScript.kt
> +                                    "with DAP on port ${debugOptions.port}"
add a translation?

2024-12-31 23:53 UTC, sqlerrorthing commented
please, review https://github.com/commandblock2/LiquidBounce/pull/1

2025-01-01 03:34 UTC, sqlerrorthing approved these changes

2025-01-01 10:27 UTC, 1zun4 approved these changes

2025-01-01 10:33 UTC, 1zun4 commented on build.gradle
> +    includeDependency "org.graalvm.polyglot:tools-community:24.0.2"
How much does this increase the file size? Also, have you confirmed the export outside the IDE as well?

2025-01-01 11:24 UTC, sqlerrorthing commented on build.gradle
> +    includeDependency "org.graalvm.polyglot:tools-community:24.0.2"
> How much does this increase the file size? Also, have you confirmed the export outside the IDE as well?

46.099mb -> 47.222mb (+2.4%)
(profiler-tool:24.0.2 -> 515.260kb)

2025-01-01 11:49 UTC, commandblock2 commented on build.gradle
> +    includeDependency "org.graalvm.polyglot:tools-community:24.0.2"
> How much does this increase the file size? Also, have you confirmed the export outside the IDE as well?

For my version of the local built .jar file it was 48.33 MB. And for the later question, yes, I have, the demo video is the one testing outside the IDE. It was, however, launched with PrismLauncher with a few mods (auto updated to latest) which might no be exactly the same version as we have in development environment, 
- [Fabric API](https://modrinth.com/mod/P7dR8mSH) [0\.114\.0\+1\.21\.4] (fabric\-api\-0\.114\.0\+1\.21\.4\.jar)
- [Fabric Language Kotlin](https://modrinth.com/mod/Ha28R6CL) [1\.13\.0\+kotlin\.2\.1\.0] (fabric\-language\-kotlin\-1\.13\.0\+kotlin\.2\.1\.0\.jar)
- [LiquidBounce](https://liquidbounce.net/) [0\.22\.1] (liquidbounce\-0\.22\.1\.jar)
- [Mod Menu](https://modrinth.com/mod/mOgUt4GM) [13\.0\.0\-beta\.1] (modmenu\-13\.0\.0\-beta\.1\.jar)
- [Placeholder API](https://modrinth.com/mod/eXts2L7r) [2\.5\.1\+1\.21\.3] (placeholder\-api\-2\.5\.1\+1\.21\.3\.jar)
- [Sodium](https://modrinth.com/mod/AANobbMI) [0\.6\.6\+mc1\.21\.4] (sodium\-fabric\-0\.6\.6\+mc1\.21\.4\.jar)
- [ViaFabricPlus](https://modrinth.com/mod/rIC2XJV4) [3\.6\.1] (ViaFabricPlus\-3\.6\.1\.jar)

2025-01-01 17:13 UTC, merged